springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  datasource:
    url: jdbc:mysql://ddd-mysql:3306/eventuate?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialization-mode: always